[package]
name = "loki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.17"
anyhow = "1.0.57"
strfmt = "0.1.6"